apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
    kubernetes.azure.com/generator: devhub
  namespace: sample-app-namespace-1731092616213
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: registry1731092764278.azurecr.io/image-workflow-1731092616185:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080